version: "3.0"

expectations:
  population_size: 100000

actions:
  generate_cohortMAIN:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_cohort2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019
    outputs:
      highly_sensitive:
        cohort: output/input_2019.csv
  
 generate_cohortSEPT2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_SEPT2020
    outputs:
      highly_sensitive:
        cohort: output/input_SEPT2020.csv
        
 generate_flowchartdata:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flow_chart
    outputs:
      highly_sensitive:
        cohort: output/input_flow_chart.csv

  run_model:
    run: stata-mp:latest analysis/model.do
    needs: [generate_cohortMAIN]
    outputs:
      moderately_sensitive:
        log: logs/model.log

  run_all:
    needs:
      - run_model
    # In order to be valid this action needs to define a run commmand and some
    # output. We don't really care what these are but the below does the trick.
    # In a future release of the platform, this special action won't need to be
    # defined at all.
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml