version: "3.0"

expectations:
  population_size: 10000

actions:
  generate_cohorts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_cohort2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019
    outputs:
      highly_sensitive:
        cohort: output/input_2019.csv
        
  generate_flowchartdata:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flow_chart
    outputs:
      highly_sensitive:
        cohort: output/input_flow_chart.csv

  crmain:
    run: stata-mp:latest analysis/cr_create_analysis_dataset.do
    needs: [generate_cohorts]
    outputs:
      highly_sensitive:
        data: analysis/cr_create_analysis_dataset.dta
        stsetdata: analysis/cr_create_analysis_dataset_STSET_ONSCSDEATH.dta
      moderately_sensitive:
        log: analysis/output/cr_create_analysis_dataset.log
  
  cr2019:
    run: stata-mp:latest analysis/cr_create_analysis_dataset_2019.do
    needs: [generate_cohort2019]
    outputs:
      highly_sensitive:
        data: analysis/cr_create_analysis_dataset_2019.dta
      moderately_sensitive:
        log: analysis/output/cr_create_analysis_dataset_2019.log
  
  descriptive_table1:
    run: stata-mp:latest analysis/an_tablecontent_PublicationDescriptivesTable.do
    needs: [crmain]
    outputs:
      moderately_sensitive:
        log: analysis/output/an_tablecontent_PublicationDescriptivesTable.txt
  
  absoluterisksbycause:
    run: stata-mp:latest analysis/an_covid_vs_othercauses_abs_AGE.do
    needs: [crmain]
    outputs:
      moderately_sensitive:
        log: analysis/output/an_covid_vs_othercauses_abs_AGE.log
        graph: analysis/output/an_covid_vs_othercauses_abs_AGE_GRAPH.svg
        estimates: analysis/output/an_covid_vs_othercauses_abs_AGE_ESTIMATES.dta

  agesexmodels:
    run: stata-mp:latest analysis/an_covidvsnoncovid_agesex.do
    needs: [crmain]
    outputs:
      moderately_sensitive:
        log: analysis/output/an_covidvsnoncovid_agesex.log
        models: analysis/output/models/an_covidvsnoncovid_agesex_*.ster
  
  fulladjmodels:
    run: stata-mp:latest analysis/an_covidvsnoncovid_full.do
    needs: [crmain]
    outputs:
      moderately_sensitive:
        log: analysis/output/an_covidvsnoncovid_full.log
        models: analysis/output/models/an_covidvsnoncovid_full_*.ster  
  
  agesex2019models:
    run: stata-mp:latest analysis/an_noncovid_2019_agesex.do
    needs: [cr2019]
    outputs:
      moderately_sensitive:
        log: analysis/output/an_noncovid_2019_agesex.log
        models: analysis/output/models/an_noncovid_2019_agesex_*.ster  
  
  
  fulladj2019models:
    run: stata-mp:latest analysis/an_noncovid_2019_full.do
    needs: [cr2019]
    outputs:
      moderately_sensitive:
        log: analysis/output/an_noncovid_2019_full.log
        models: analysis/output/models/an_noncovid_2019_full_*.ster  
    
  covnoncov_forestplot:
    run: stata-mp:latest analysis/an_processout_agesex_covvsnon_forestplots.do
    needs: [agesexmodels]
    outputs:
      moderately_sensitive:
        log: analysis/output/an_processout_agesex_covvsnon_forestplots_TABLE.txt
        graph: analysis/output/an_processout_agesex_covvsnon_forestplots_GRAPH.svg
 
  covnoncov_appxestimatestable:
    run: stata-mp:latest analysis/an_processout_agesex_covvsnon_table.do
    needs: 
      - agesexmodels 
      - fulladjmodels 
      - agesex2019models 
      - fulladj2019models
    outputs:
      moderately_sensitive:
        log: analysis/output/an_processout_agesex_covvsnon_table.txt
 
 
  ethnicity_model_and_graph:
    run: stata-mp:latest analysis/an_ethnicitybycod_logisticversion.do
    needs: [crmain]
    outputs:
      moderately_sensitive:
        log: analysis/output/an_ethnicitybycod_logisticversion.log
        graph: analysis/output/an_ethnicitybycod_logisticversion.svg
 
  deathsonly_models:
    run: stata-mp:latest analysis/an_deathsonlyanalysis.do
    needs: [crmain]
    outputs:
      moderately_sensitive:
        log: analysis/output/an_deathsonlyanalysis.log
        models: analysis/output/models/an_deathsonlyanalysis_*.ster  
   
  deathsonly_ORfigure:
    run: stata-mp:latest analysis/an_processout_deathsonlyanalysis.do
    needs: [deathsonly_models]
    outputs:
      moderately_sensitive:
        log: analysis/output/an_processout_deathsonlyanalysis_TABLE.txt
        graph: analysis/output/an_processout_deathsonlyanalysis_GRAPH.svg 
   
  run_model:
    run: stata-mp:latest analysis/model.do
    needs: [generate_cohorts]
    outputs:
      moderately_sensitive:
        log: logs/model.log

  run_all:
    needs:
      - run_model
    # In order to be valid this action needs to define a run commmand and some
    # output. We don't really care what these are but the below does the trick.
    # In a future release of the platform, this special action won't need to be
    # defined at all.
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml